[package]
name = "netwc"
version = "0.1.0"
authors = ["Paul Lysak <paul.lysak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#crossbeam = "0.7.2"
rayon = "1.2.0"
tokio = "1.8"
